version: '3.8'

services:
  # MongoDB
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - kafka-network
    restart: always

  # PostgreSQL
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - kafka-network
    restart: always

  # Consumer Mongo
  consumer-mongo:
    image: iker186/consumer-mongo:latest
    environment:
      KAFKA_SERVER: ${KAFKA_SERVER}  # Redpanda Kafka Server
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      MONGO_URI: ${MONGO_URI}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
    depends_on:
      - mongo
    networks:
      - kafka-network
    restart: always

  # Consumer PostgreSQL
  consumer-postgres:
    image: iker186/consumer-postgres:latest
    environment:
      KAFKA_SERVER: ${KAFKA_SERVER}  # Redpanda Kafka Server
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_URI: ${POSTGRES_URI}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
    depends_on:
      - postgres
    networks:
      - kafka-network
    restart: always

  # Producer Mongo
  producer-mongo:
    image: iker186/producer-mongo:latest
    environment:
      KAFKA_SERVER: ${KAFKA_SERVER}  # Redpanda Kafka Server
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      MONGO_URI: ${MONGO_URI}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
    depends_on:
      - mongo
    networks:
      - kafka-network
    restart: always

  # Producer PostgreSQL
  producer-postgres:
    image: iker186/producer-postgres:latest
    environment:
      KAFKA_SERVER: ${KAFKA_SERVER}  # Redpanda Kafka Server
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_URI: ${POSTGRES_URI}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
    depends_on:
      - postgres
    networks:
      - kafka-network
    restart: always

networks:
  kafka-network:
    driver: bridge

volumes:
  mongo-data:
